// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dabqahjxfzzxxcyaanws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhYnFhaGp4Znp6eHhjeWFhbndzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MzQ0MjYsImV4cCI6MjA1ODUxMDQyNn0.nR_lk7cjQTqqcZowhKTI1q98xTaIb9M88ioz1JDX2MU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);